### PR TITLE
#216: added db.listCollections

### LINKED ISSUE #216: Any way to get all collections?
Thanks for a great library!

Currently I'm using `db._db.listCollections().toArray()` but since in my understanding `_db` is not public API, this feels bit hackish and might not work in the future?

### PR DESCRIPTION
**Pull request by janek26**
Provides a method to access `listCollections` without using `db._db`.
If the Mongo API will change in future releases, the Monk Team/Community just have to care about this method, as the `db._db` property is not meant to be used by Monk users. 

For further details:
closes #216

### CODE REVIEW

File: lib/manager.js [hunk 1]
```diff
@@ -243,6 +243,18 @@ Manager.prototype.close = function (force, fn) {
...
 /**
+ * Lists all collections.
+ *
+ * @param {Object} [query] - A query expression to filter the list of collections.
+ * @return {Array} array of all collections
+ */
+
+Manager.prototype.listCollections = function (query) {
+  if (!query) query = undefined
+  return this._db.listCollections(query).toArray()
```
Comment (mathieudutour) [inline lib/manager.js]: pretty sure you need to use `this.executeWhenOpened().then(function (db) {...})` so that it's only executed when the connection is opened

File: lib/manager.js [hunk 2]
```diff
@@ -243,6 +243,18 @@ Manager.prototype.close = function (force, fn) {
...
 
 /**
+ * Lists all collections.
+ *
+ * @param {Object} [query] - A query expression to filter the list of collections.
+ * @return {Array} array of all collections
+ */
+
+Manager.prototype.listCollections = function (query) {
+  if (!query) query = undefined
```
Comment (mathieudutour) [inline lib/manager.js]: why is that useful?

**Comment by janek26** [comment]
@mathieudutour changes should be applied

**Comment by janek26** [comment]
somehow travis continues failing in some `update` test, but I never changed a thing in `update` or touched any of the functions used by `update`

**Comment by bobmoff** [comment]
Great work, I am looking forward to this functionality

**Comment by janek26** [comment]
Thx @bobmoff :+1:
@mathieudutour all travis checks have passed, please consider to do a second code review

File: lib/manager.js [hunk 3]
```diff
@@ -243,6 +243,19 @@ Manager.prototype.close = function (force, fn) {
...
 /**
+ * Lists all collections.
+ *
+ * @param {Object} [query] - A query expression to filter the list of collections.
+ * @return {Array} array of all collections
+ */
+
+Manager.prototype.listCollections = function (query) {
+  return this.executeWhenOpened().then(function (db) {
+    return db.listCollections(query).toArray()
```
Comment (mathieudutour) [inline lib/manager.js]: could we perhaps return a list of monk collection? that would be a lot useful

**Comment by janek26** [comment]
@mathieudutour check again please :+1:
